---
timestamp_urls:
  - http://timestamp.comodoca.com
  - http://timestamp.apple.com/ts01
  - http://tsa.starfieldtech.com
  - http://tsp.iaik.tugraz.at/tsp/TspRequest
  - http://timestamp.digicert.com
  - http://timestamp.globalsign.com/scripts/timstamp.dll

products:
  auditbeat-oss:
    description: Audit the activities of users and processes on your system
    published_name: Elastic Beats Autditbeat OSS
    published_url: https://www.elastic.co/products/beats/auditbeat
    published_binaries: [ auditbeat.exe ]
    mutable_dirs: [ ]
    service: true

  lsbeat:
    description: lsbeat
    published_name: Mirero System Beats Lsbeat
    published_url: http://www.mirero.co.kr/
    published_binaries: [ lsbeat.exe ]
    mutable_dirs: [ ]
    service: true

  filebeat-oss:
    description: Filebeat sends log files to Logstash or directly to Elasticsearch
    published_name: Elastic Beats Filebeat OSS
    published_url: https://www.elastic.co/products/beats/filebeat
    published_binaries: [ filebeat.exe ]
    mutable_dirs: [ modules.d, module, kibana ]
    service: true

  heartbeat-oss:
    description: Ping remote services for availability and log results to Elasticsearch or send to Logstash
    published_name: Elastic Beats Heartbeat OSS
    published_url: https://www.elastic.co/products/beats/heartbeat
    published_binaries: [ heartbeat.exe ]
    mutable_dirs: [ monitors.d ]
    service: true

  metricbeat-oss:
    description: Metricbeat is a lightweight shipper for metrics
    published_name: Elastic Beats Metricbeat OSS
    published_url: https://www.elastic.co/products/beats/metricbeat
    published_binaries: [ metricbeat.exe ]
    mutable_dirs: [ modules.d, module, kibana ]
    service: true

  packetbeat-oss:
    description: Packetbeat analyzes network traffic and sends the data to Elasticsearch
    published_name: Elastic Beats Packetbeat OSS
    published_url: https://www.elastic.co/products/beats/packetbeat
    published_binaries: [ packetbeat.exe ]
    mutable_dirs: [ ]
    service: true

  winlogbeat-oss:
    description: Winlogbeat ships Windows event logs to Elasticsearch or Logstash
    published_name: Elastic Beats Winlogbeat OSS
    published_url: https://www.elastic.co/products/beats/winlogbeat
    published_binaries: [ winlogbeat.exe ]
    mutable_dirs: [ ]
    service: true
